# Generated by Django 5.2.7 on 2026-04-16 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('cognoms', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefon', models.CharField(blank=True, max_length=20, null=True)),
                ('actiu', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Alumne',
                'verbose_name_plural': 'Alumnes',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('cognoms', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefon', models.CharField(blank=True, max_length=20, null=True)),
                ('preu_hora', models.DecimalField(decimal_places=2, help_text='Preu que cobra el profe per hora', max_digits=5)),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professors',
            },
        ),
        migrations.CreateModel(
            name='PagamentAlumne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('import_pagat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('concepte', models.CharField(blank=True, max_length=255, null=True)),
                ('metode_pagament', models.CharField(choices=[('Efectiu', 'Efectiu'), ('Transferencia', 'Transferència'), ('Bizum', 'Bizum')], default='Efectiu', max_length=50)),
                ('alumne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagaments', to='gestio.alumne')),
            ],
            options={
                'verbose_name': 'Pagament Alumne',
                'verbose_name_plural': 'Pagaments Alumnes',
            },
        ),
        migrations.CreateModel(
            name='PagamentProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('import_pagat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('concepte', models.CharField(blank=True, max_length=255, null=True)),
                ('metode_pagament', models.CharField(choices=[('Efectiu', 'Efectiu'), ('Transferencia', 'Transferència'), ('Bizum', 'Bizum')], default='Efectiu', max_length=50)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagaments_rebuts', to='gestio.professor')),
            ],
            options={
                'verbose_name': 'Pagament Professor',
                'verbose_name_plural': 'Pagaments Professors',
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inici', models.TimeField()),
                ('durada_minuts', models.PositiveIntegerField(default=60)),
                ('preu_classe', models.DecimalField(decimal_places=2, help_text="Preu que paga l'alumne per aquesta classe", max_digits=6)),
                ('comentaris', models.TextField(blank=True, null=True)),
                ('alumne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='gestio.alumne')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='gestio.professor')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
            },
        ),
    ]
