# Generated by Django 5.2.7 on 2026-04-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestio', '0002_alumne_preu_per_hora_professor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumne',
            name='adreca',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alumne',
            name='email_pare',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='alumne',
            name='nom_centre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alumne',
            name='telefon_pare',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
